import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  ar: {
    'nav.home': 'الرئيسية',
    'nav.allQuestions': 'جميع الأسئلة',
    'nav.exam': 'اختبار',
    'nav.about': 'عن المنصة',
    'nav.book': 'الكتاب',
    'nav.testCreed': 'اختبر عقيدتك',
    'nav.dashboard': 'لوحة التحكم',
    'nav.login': 'دخول',
    'nav.register': 'إنشاء حساب',
    'nav.logout': 'تسجيل الخروج',
    'home.hero.badge': 'منهج أهل السنة والجماعة',
    'home.hero.title_part1': 'تعلّم ',
    'home.hero.title_part2': 'العقيدة',
    'home.hero.title_part3': ' بأسلوب مبتكر',
    'home.hero.subtitle': 'منهج تعليمي منظم لعرض مئتي سؤال وجواب في العقيدة الإسلامية الصحيحة مقسمة إلى أقسام متعددة لتسهيل الفهم والمراجعة.',
    'home.hero.start': 'ابدأ التعلّم الآن',
    'home.hero.exam': 'اختبار',
    'home.hero.download': 'تحميل الكتاب PDF',
    'home.stats.users': 'مستفيد',
    'home.stats.sections': 'أقسام شاملة',
    'home.stats.minutes': 'دقيقة مرئية',
    'home.stats.questions': 'سؤال وجواب',
    'home.features.title': 'لماذا ',
    'home.features.title_highlight': 'يُشرح؟',
    'home.features.f1.title': 'شرح واقعي حي',
    'home.features.f1.desc': 'طرح معاصر يربط مسائل الاعتقاد بواقع المسلم العملي وتحديات العصر الحالية.',
    'home.features.f2.title': 'تصميم عصري',
    'home.features.f2.desc': 'واجهة مريحة بصرياً مدعومة بألوان وإضافات تساعد على التركيز في التعلم.',
    'home.features.f3.title': 'بحث متقدم',
    'home.features.f3.desc': 'إمكانية البحث في الأسئلة والإجابات للوصول المباشر للمعلومة.',
    'home.features.f4.title': 'محتوى موثوق',
    'home.features.f4.desc': 'مراجعة دقيقة لجميع المسائل لتتوافق مع المصادر الأصلية للاعتقاد.',
    'home.explore.title': 'استكشف ',
    'home.explore.title_highlight': 'الأسئلة',
    'home.explore.all': 'الكل',
    'home.explore.intro': 'المقدمات',
    'home.explore.tawhid': 'التوحيد',
    'home.explore.worship': 'العبادة',
    'home.explore.browse_all': 'تصفح جميع الأسئلة',
    'home.book.title': 'عن كتاب ',
    'home.book.title_highlight': '200 سؤال وجواب',
    'home.book.desc': 'تأليف العلامة حافظ بن أحمد الحكمي، وهو من أعظم المختصرات التي جمعت أصول الدين بأسلوب السؤال والجواب، مما يسهل على طالب العلم والمسلم العامي استيعابها وفهمها.',
    'home.contact.title': 'تواصل ',
    'home.contact.title_highlight': 'معنا',
    'home.contact.name': 'الاسم الكريم',
    'home.contact.email': 'البريد الإلكتروني',
    'home.contact.subject': 'الموضوع',
    'home.contact.message': 'الرسالة...',
    'home.contact.send': 'إرسال الرسالة',
    'questions.title': 'جميع الأسئلة والأجوبة',
    'questions.search': 'ابحث في الأسئلة أو الإجابات...',
    'questions.category': 'التصنيف',
    'questions.all': 'الكل',
    'questions.no_results': 'لم يتم العثور على نتائج مطابقة لبحثك',
    'questions.back': 'العودة لجميع الأسئلة',
    'questions.prev': 'السؤال السابق',
    'questions.next': 'السؤال التالي',
    'questions.similar': 'أسئلة مشابهة',
    'footer.description': 'منصة تعليمية تهدف إلى تبسيط وتقريب مسائل العقيدة بأسلوب عصري سهل وفق منهج أهل السنة والجماعة.',
    'footer.quick_links': 'روابط سريعة',
    'footer.sections': 'الأقسام',
    'footer.account': 'الحساب',
    'auth.welcome': 'أهلاً بعودتك إلى منصة العقيدة',
    'auth.login_google': 'دخول بواسطة Google',
    'auth.or_email': 'أو عبر البريد الإلكتروني',
    'auth.email_required': 'البريد الإلكتروني مطلوب',
    'auth.email_invalid': 'صيغة البريد غير صحيحة',
    'auth.password_required': 'كلمة المرور مطلوبة',
    'auth.password_short': 'كلمة المرور 6 أحرف على الأقل',
    'auth.loading': 'جارٍ التحميل...',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.have_account': 'لديك حساب بالفعل؟',
    'auth.success_login_title': 'تم تسجيل الدخول',
    'auth.success_login_msg': 'أهلاً بك مجددًا في منصة العقيدة',
    'auth.error_login_title': 'خطأ في الدخول',
    'auth.error_google_msg': 'فشل الاتصال بـ Google، حاول مرة أخرى',
    'auth.name_required': 'الاسم مطلوب',
    'auth.passwords_not_match': 'كلمتا المرور غير متطابقتين',
    'auth.success_reg_title': 'تم إنشاء الحساب',
    'auth.success_reg_msg': 'أهلاً بك في منصة العقيدة، تم التسجيل بنجاح',
    'auth.error_reg_title': 'خطأ في التسجيل',
    'auth.pwd_weak': 'ضعيفة',
    'auth.pwd_medium': 'متوسطة',
    'auth.pwd_good': 'جيدة',
    'dash.welcome': 'أهلاً وسهلاً،',
    'dash.visitor': 'زائر',
    'dash.logout': 'تسجيل الخروج',
    'dash.stat_qa': 'سؤال وجواب',
    'dash.stat_quiz': 'سؤال اختبار',
    'dash.stat_sections': 'قسمًا شاملًا',
    'dash.quiz_title': 'اختبر عقيدتك',
    'dash.quiz_desc': 'اختبر معلوماتك وعلمك بالعقيدة الإسلامية بأسلوب السؤال والجواب المتعدد.',
    'dash.quiz_cta': 'ابدأ الاختبار الآن',
    'dash.browse_title': 'استكشف الأسئلة',
    'dash.browse_desc': 'تصفَّح مئتي سؤال وجواب في العقيدة الإسلامية مقسَّمة إلى أقسام متعددة مع إمكانية البحث والتصفية.',
    'dash.browse_cta': 'تصفح الأسئلة',
    'dash.quick_links': 'روابط سريعة',
    'dash.home': 'الصفحة الرئيسية',
    'dash.interactive': 'الاختبار التفاعلي',
    'quiz.questions': 'سؤالاً',
    'quiz.options': 'خيارات',
    'quiz.points': 'النقاط',
    'quiz.question_label': 'السؤال',
    'quiz.out_of': 'من',
    'quiz.correct_answer': 'إجابة صحيحة! 🎉',
    'quiz.correct_is': 'الإجابة الصحيحة هي:',
    'quiz.restart': 'إعادة الاختبار',
    'quiz.completed': 'اكتمل الاختبار!',
    'quiz.completed_msg': 'لقد حصلت على {score} من {total}',
    'quiz.finished': 'انتهى الاختبار!',
    'quiz.correct_count': '{count} صحيحة',
    'quiz.wrong_count': '{count} خاطئة',
    'quiz.score_excellent': 'ممتاز! تبارك الله',
    'quiz.score_very_good': 'جيد جداً، أحسنت',
    'quiz.score_good': 'جيد، استمر في المراجعة',
    'quiz.score_needs_review': 'تحتاج مراجعة أكثر للكتاب',
    'quiz.exit': 'خروج',
    'exam.title': 'اختبار العقيدة الإسلامية',
    'exam.subtitle': 'اختبر مستواك في مادة العقيدة بـ {total} سؤالاً من اختيار متعدد.',
    'exam.result_msg': 'ستظهر النتيجة التفصيلية بعد إتمام الاختبار فقط.',
    'exam.navigation': 'التنقل',
    'exam.nav_free': 'حر',
    'exam.notice': 'لن تظهر الإجابات الصحيحة أثناء الاختبار — ستظهر في تقرير النتيجة فقط.',
    'exam.result_title': 'نتيجة الاختبار',
    'exam.answered': 'مُجاب',
    'exam.skipped': 'غير مجاب',
    'exam.review_answers': 'مراجعة الأجوبة',
    'exam.detailed_review': 'مراجعة تفصيلية للإجابات',
    'exam.not_answered_msg': 'لم تُجِب على هذا السؤال',
    'exam.your_answer': 'إجابتك:',
    'exam.correct_is': 'الصحيحة:',
    'exam.warning_unanswered': 'لديك {count} سؤال لم تُجِب عليه بعد.',
    'exam.warning_prompt': 'هل تريد الإنهاء والحصول على نتيجتك؟',
    'exam.finish_now': 'إنهاء الآن',
    'exam.continue_answering': 'متابعة الإجابة',
    'exam.finished_cta': 'إنهاء وعرض النتيجة',
    'exam.completed': 'مكتمل',
    'exam.remaining': 'سؤال متبقٍ',
  },
  en: {
    'nav.home': 'Home',
    'nav.allQuestions': 'All Questions',
    'nav.exam': 'Exam',
    'nav.about': 'About',
    'nav.book': 'The Book',
    'nav.testCreed': 'Test Your Creed',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'home.hero.title': '200 Questions & Answers in Creed',
    'home.hero.badge': 'Methodology of Ahlus-Sunnah wal-Jama\'ah',
    'home.hero.title_part1': 'Learn ',
    'home.hero.title_part2': 'Creed',
    'home.hero.title_part3': ' in an Innovative Way',
    'home.hero.subtitle': 'A structured educational methodology presenting 200 questions and answers on the correct Islamic Creed, divided into multiple sections to facilitate understanding and review.',
    'home.hero.start': 'Start Learning Now',
    'home.hero.exam': 'Exam',
    'home.hero.download': 'Download PDF',
    'home.stats.users': 'Beneficiaries',
    'home.stats.sections': 'Comprehensive Sections',
    'home.stats.minutes': 'Video Minutes',
    'home.stats.questions': 'Questions & Answers',
    'home.features.title': 'Why ',
    'home.features.title_highlight': 'Explain?',
    'home.features.f1.title': 'Lively Explanation',
    'home.features.f1.desc': 'A contemporary approach linking creed issues with the practical reality of Muslims and current challenges.',
    'home.features.f2.title': 'Modern Design',
    'home.features.f2.desc': 'A visually comfortable interface supported by colors and additions that help focus on learning.',
    'home.features.f3.title': 'Advanced Search',
    'home.features.f3.desc': 'Ability to search within questions and answers for direct access to information.',
    'home.features.f4.title': 'Trusted Content',
    'home.features.f4.desc': 'Accurate review of all matters to comply with the original sources of creed.',
    'home.explore.title': 'Explore ',
    'home.explore.title_highlight': 'Questions',
    'home.explore.all': 'All',
    'home.explore.intro': 'Introductions',
    'home.explore.tawhid': 'Tawhid',
    'home.explore.worship': 'Worship',
    'home.explore.browse_all': 'Browse All Questions',
    'home.book.title': 'About the Book ',
    'home.book.title_highlight': '200 Questions & Answers',
    'home.book.desc': 'Authored by the scholar Hafiz bin Ahmed al-Hakami, it is one of the greatest summaries that gathered the fundamentals of religion in a Q&A style, making it easy for students of knowledge and laypeople to grasp and understand.',
    'home.contact.title': 'Connect ',
    'home.contact.title_highlight': 'With Us',
    'home.contact.name': 'Name',
    'home.contact.email': 'Email',
    'home.contact.subject': 'Subject',
    'home.contact.message': 'Message...',
    'home.contact.send': 'Send Message',
    'questions.title': 'All Questions & Answers',
    'questions.search': 'Search questions or answers...',
    'questions.category': 'Category',
    'questions.all': 'All',
    'questions.no_results': 'No results found matching your search',
    'questions.back': 'Back to all questions',
    'questions.prev': 'Previous Question',
    'questions.next': 'Next Question',
    'questions.similar': 'Similar Questions',
    'footer.description': 'An educational platform aimed at simplifying creed issues in an easy, modern way according to the methodology of Ahlus-Sunnah wal-Jama\'ah.',
    'footer.quick_links': 'Quick Links',
    'footer.sections': 'Sections',
    'footer.account': 'Account',
    'auth.welcome': 'Welcome back to the Aqida Platform',
    'auth.login_google': 'Sign in with Google',
    'auth.or_email': 'Or via email',
    'auth.email_required': 'Email is required',
    'auth.email_invalid': 'Invalid email format',
    'auth.password_required': 'Password is required',
    'auth.password_short': 'Password must be at least 6 characters',
    'auth.loading': 'Loading...',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.success_login_title': 'Logged in successfully',
    'auth.success_login_msg': 'Welcome back to the Aqida platform',
    'auth.error_login_title': 'Login Error',
    'auth.error_google_msg': 'Failed to connect to Google, try again',
    'auth.name_required': 'Name is required',
    'auth.passwords_not_match': 'Passwords do not match',
    'auth.success_reg_title': 'Account created',
    'auth.success_reg_msg': 'Welcome to the Aqida platform, registration successful',
    'auth.error_reg_title': 'Registration Error',
    'auth.pwd_weak': 'Weak',
    'auth.pwd_medium': 'Medium',
    'auth.pwd_good': 'Good',
    'dash.welcome': 'Welcome,',
    'dash.visitor': 'Visitor',
    'dash.logout': 'Logout',
    'dash.stat_qa': 'Q&A',
    'dash.stat_quiz': 'Quiz Questions',
    'dash.stat_sections': 'Comprehensive Sections',
    'dash.quiz_title': 'Test Your Creed',
    'dash.quiz_desc': 'Test your knowledge of Islamic creed using multiple-choice questions.',
    'dash.quiz_cta': 'Start Quiz Now',
    'dash.browse_title': 'Explore Questions',
    'dash.browse_desc': 'Browse 200 questions and answers in Islamic creed divided into multiple sections.',
    'dash.browse_cta': 'Browse Questions',
    'dash.quick_links': 'Quick Links',
    'dash.home': 'Home Page',
    'dash.interactive': 'Interactive Quiz',
    'quiz.questions': 'Questions',
    'quiz.options': 'Options',
    'quiz.points': 'Points',
    'quiz.question_label': 'Question',
    'quiz.out_of': 'out of',
    'quiz.correct_answer': 'Correct Answer! 🎉',
    'quiz.correct_is': 'The correct answer is:',
    'quiz.restart': 'Restart Quiz',
    'quiz.completed': 'Quiz Completed!',
    'quiz.completed_msg': 'You scored {score} out of {total}',
    'quiz.finished': 'Quiz Finished!',
    'quiz.correct_count': '{count} Correct',
    'quiz.wrong_count': '{count} Wrong',
    'quiz.score_excellent': 'Excellent! MashaAllah',
    'quiz.score_very_good': 'Very Good, Well Done',
    'quiz.score_good': 'Good, Keep Reviewing',
    'quiz.score_needs_review': 'Needs more study of the book',
    'quiz.exit': 'Exit',
    'exam.title': 'Islamic Creed Exam',
    'exam.subtitle': 'Test your level in the creed subject with {total} multiple-choice questions.',
    'exam.result_msg': 'Detailed results will only appear after completing the exam.',
    'exam.navigation': 'Navigation',
    'exam.nav_free': 'Free',
    'exam.notice': 'Correct answers will not be shown during the exam — they will appear in the result report only.',
    'exam.result_title': 'Exam Result',
    'exam.answered': 'Answered',
    'exam.skipped': 'Unanswered',
    'exam.review_answers': 'Review Answers',
    'exam.detailed_review': 'Detailed Answer Review',
    'exam.not_answered_msg': 'You did not answer this question',
    'exam.your_answer': 'Your answer:',
    'exam.correct_is': 'Correct:',
    'exam.warning_unanswered': 'You have {count} unanswered questions.',
    'exam.warning_prompt': 'Do you want to finish and get your result?',
    'exam.finish_now': 'Finish Now',
    'exam.continue_answering': 'Continue Answering',
    'exam.finished_cta': 'Finish and Show Result',
    'exam.completed': 'Completed',
    'exam.remaining': 'Questions remaining',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
